# Generated by Django 5.0.7 on 2024-08-03 23:19

import apps.buildings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("size", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("main_image", models.ImageField(upload_to="images/")),
                (
                    "panorama",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.buildings.models.upload_panorama,
                        verbose_name="Panorama",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="category.category",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="post_images", to="buildings.image"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="buildings.post",
                        verbose_name="родитель",
                    ),
                ),
                ("services", models.ManyToManyField(to="buildings.service")),
            ],
        ),
    ]
